"""Onboarding tests — generate a DRAFT AGENTS.md on first touch of a repo.

`onboard` is a 4th task kind that mirrors the `review_repository` read-only
path but is allowed to write a single file (AGENTS.md). It captures repo
COMPREHENSION ("what is": stack, layout, build/test, conventions, gotchas) so
1b's project-guide briefing has something to read on repos that lack one. The
draft is human-reviewed (not authoritative until then), so when an AGENTS.md
already exists the agent validates-and-keeps rather than clobbering.

Two layers, both SDK-/docker-/claude-free: the goal-wrapper prompt (runner) and
the TaskQueue wiring (a stub engine stands in for OpenHands).
"""

import importlib.util
import os
from pathlib import Path

import pytest

from devclaw.engine import EngineRequest
from devclaw.state_store import StateStore
from devclaw.task_queue import TaskQueue

_RUNNER_PATH = Path(__file__).resolve().parents[1] / "openhands-runner" / "runner.py"


@pytest.fixture(scope="module")
def runner():
    spec = importlib.util.spec_from_file_location("oh_runner_under_test", _RUNNER_PATH)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)  # top-level only; main() (and its SDK imports) is not run
    return mod


# ---- the onboard goal-wrapper ----------------------------------------------


def test_onboard_writes_a_draft_agents_md(runner):
    wrapped = runner._wrap_goal("onboard", "FOCUS-TOKEN")
    # writes the comprehension file, marked a draft for human review
    assert "AGENTS.md" in wrapped
    assert "DRAFT" in wrapped
    # the optional focus still rides along
    assert "FOCUS-TOKEN" in wrapped


def test_onboard_is_read_only_except_agents_md(runner):
    wrapped = runner._wrap_goal("onboard", "")
    assert "READ ONLY" in wrapped
    # the only write it's permitted is AGENTS.md (every OTHER file is off-limits)
    assert "EXCEPT" in wrapped
    assert "do not change" in wrapped or "Do NOT modify" in wrapped


def test_onboard_captures_comprehension_not_direction(runner):
    wrapped = runner._wrap_goal("onboard", "")
    # the "what is" comprehension surface, incl. the verify-gate command
    for cue in ("Stack", "Layout", "test", "gate", "Conventions", "gotcha"):
        assert cue.lower() in wrapped.lower(), cue
    # direction / decision-log is deliberately OUT of scope
    assert "decision log" in wrapped.lower()
    assert "out of scope" in wrapped.lower()


def test_onboard_keeps_a_correct_existing_agents_md(runner):
    wrapped = runner._wrap_goal("onboard", "")
    # validate-and-keep, not clobber, when AGENTS.md already exists
    assert "ALREADY exists" in wrapped
    assert "KEEP" in wrapped
    assert "unchanged" in wrapped


def test_onboard_kind_is_distinct_from_review(runner):
    assert runner._wrap_goal("onboard", "X") != runner._wrap_goal("review_repository", "X")


# ---- TaskQueue wiring (stub engine, no docker/claude) ----------------------


def _onboard_runner():
    """Stub engine that does what the real onboard agent does to the workspace:
    write AGENTS.md and report ok. No verify gate is involved for onboarding."""

    async def runner(req: EngineRequest):
        assert req.kind == "onboard"
        assert req.verify_cmd is None  # onboarding has no gate
        with open(os.path.join(req.workspace_dir, "AGENTS.md"), "w") as f:
            f.write("# DRAFT — generated by devclaw onboarding\n")
        return {
            "status": "ok",
            "workspaceDir": req.workspace_dir,
            "message": "onboarding completed.",
        }

    return runner


@pytest.fixture()
def store(tmp_path):
    s = StateStore(str(tmp_path / "t.db"))
    yield s
    s.close()


async def test_onboard_task_settles_done_and_writes_agents_md(store, tmp_path):
    ws = str(tmp_path / "ws")
    os.makedirs(ws)
    q = TaskQueue(store, runner=_onboard_runner())
    tid = q.submit(kind="onboard", workspace_dir=ws, goal="general onboarding")
    await q.drain()

    t = store.get_task(tid)
    assert t.status == "done"
    assert t.kind == "onboard"
    assert os.path.exists(os.path.join(ws, "AGENTS.md"))


async def test_onboard_task_does_not_gate_or_deliver(store, tmp_path):
    """Onboarding is comprehension, not a code change: no verify gate, no PR —
    the human reviews the draft. The submit path leaves both off."""
    ws = str(tmp_path / "ws2")
    os.makedirs(ws)
    q = TaskQueue(store, runner=_onboard_runner())
    tid = q.submit(kind="onboard", workspace_dir=ws, goal="general onboarding")
    await q.drain()

    t = store.get_task(tid)
    assert t.verify_cmd is None
    assert t.deliver is False
    assert t.pr_url is None


def test_onboard_kind_round_trips_through_the_store(store):
    store.create_task(id="ob1", kind="onboard", workspace_dir="/ws", goal="g")
    assert store.get_task("ob1").kind == "onboard"
    assert store.list_tasks(kind="onboard")[0].id == "ob1"
