"""The next-action planner — the goal layer's first cognition call.

Folded in from goalclaw. Fired ONLY when the cheap check found real work. Same
mechanism/cognition split as devclaw's DAG planner: Claude decides, Python
validates the JSON. It decides the *next action* toward a goal — it does NOT
decompose code (that's start_program) and it does NOT judge direction (that's
goal_evaluator). Light reasoning → the sonnet tier by default.

Cognition reuses devclaw's own ``claude --print`` caller (``planner.claude_with_model``)
rather than the Agent SDK goalclaw used standalone: one cognition mechanism for
the whole service, no extra dependency, and it bills the Pro/Max OAuth session
directly — which (from 2026-06-15) draws from a different pool than the Agent SDK,
so ``--print`` is also the safer quota choice for a recurring loop.
"""

from __future__ import annotations

import json
import os
import re
from typing import Awaitable, Callable

from .goal_models import Action, Goal, GoalStatus, PlanResult

ClaudeCaller = Callable[[str], Awaitable[str]]

_VALID_TOOLS = {"start_program", "implement_feature", "fix_bug", "review_repository"}
_VALID_DECISIONS = {"act", "sleep", "blocked", "done"}

#: the goal planner's model tier (bounded JSON, light reasoning → sonnet)
GOAL_PLANNER_MODEL = os.environ.get("DEVCLAW_GOAL_PLANNER_MODEL", "sonnet") or None


class GoalPlannerError(Exception):
    def __init__(self, message: str, raw: str | None = None) -> None:
        super().__init__(message)
        self.raw = raw


SYSTEM_PROMPT = """You are DevClaw's goal planner. You drive ONE durable goal
forward across many wakeups. On each wakeup you see the goal, its current state,
recent history, any new steering, and the result of the action that just finished
(if any). You decide the SINGLE next step.

You do NOT write code and you do NOT decompose work into a DAG — the engine does
that. You choose ONE action and hand it to the engine, or you decide there is
nothing to do, that you are blocked, or that the goal looks complete.

Rules:
- Exactly one action at a time. The engine runs it to a reviewable PR before you
  pick the next; keep momentum, don't fan out.
- Draw the next action from the goal's backlog, done_when, and any steering.
  Prefer the smallest shippable next increment.
- If the finished action FAILED, decide: retry with a tighter instruction, pick a
  different next step, or block and ask. Don't loop on the same failure.
- Honor new steering over the backlog — it is direction, not a suggestion. Some
  steering is auto-generated by the direction evaluator (marked [auto-eval]); it
  carries the same weight — it is a correction grounded in what actually shipped.
- Use "start_program" for a goal-sized chunk the engine should decompose itself;
  "implement_feature" / "fix_bug" for a single bounded change; "review_repository"
  for a read-only assessment.
- Block ONLY when you genuinely need a human decision (ambiguous requirement,
  external credential, product call). Asking is friction — prefer to act.
- Choose "done" when the backlog is exhausted AND done_when looks satisfied by
  the history. Do NOT over-trust a bare engine "ok": delivery evidence (a PR url,
  a passed gate) is what counts. Your "done" is a PROPOSAL — it triggers a
  grounded verification before the goal actually closes — so propose it as soon as
  the work looks complete; don't keep dispatching busy-work to be safe.

Respond with STRICT JSON ONLY — no prose, no markdown fences. Schema:

{
  "decision": "act" | "sleep" | "blocked" | "done",
  "note": "<one-line human summary of this decision, for the log + Telegram>",
  "actions": [            // present iff decision == "act"; exactly one element
    {
      "tool": "start_program" | "implement_feature" | "fix_bug" | "review_repository",
      "goal": "<concrete instruction for the engine>",
      "open_pr": true
    }
  ],
  "question": "<present iff decision == 'blocked' — what you need from a human>"
}"""


def build_prompt(
    goal: Goal,
    status: GoalStatus,
    recent_log: str,
    steering: str,
    finished_detail: str,
) -> str:
    backlog = "\n".join(f"  - {b}" for b in goal.backlog) or "  (none listed)"
    parts = [
        SYSTEM_PROMPT,
        "\n## Goal",
        f"id: {goal.id}",
        f"objective: {goal.objective}",
        f"done_when: {goal.done_when or '(not specified)'}",
        f"engine: {goal.engine}  workspace_dir: {goal.workspace_dir}",
        f"verify_cmd: {goal.verify_cmd or '(none)'}",
        "backlog:",
        backlog,
        "\n## Current state",
        f"phase: {status.phase}",
        f"next (intended): {status.next or '(none)'}",
    ]
    if status.last_eval_verdict:
        parts.append(f"last direction eval: {status.last_eval_verdict} — {status.last_eval_note}")
    parts += [
        "\n## Recent history (log)",
        recent_log or "(no events yet)",
    ]
    if finished_detail:
        parts += ["\n## The action that just finished (engine result)", finished_detail]
    if steering:
        parts += ["\n## NEW steering (honor this)", steering]
    parts.append("\nReturn the JSON now.")
    return "\n".join(parts)


def extract_json(text: str) -> str:
    trimmed = text.strip()
    if trimmed.startswith("{"):
        return trimmed
    fence = re.search(r"```(?:json)?\s*(\{[\s\S]*?\})\s*```", trimmed)
    if fence and fence.group(1):
        return fence.group(1)
    first, last = trimmed.find("{"), trimmed.rfind("}")
    if first >= 0 and last > first:
        return trimmed[first : last + 1]
    raise GoalPlannerError("No JSON object found in planner response", text)


def validate(parsed: object) -> PlanResult:
    if not isinstance(parsed, dict):
        raise GoalPlannerError("Plan must be a JSON object")
    decision = parsed.get("decision")
    if decision not in _VALID_DECISIONS:
        raise GoalPlannerError(f"decision must be one of {_VALID_DECISIONS}, got {decision!r}")
    note = str(parsed.get("note", "")).strip()

    if decision == "blocked":
        question = str(parsed.get("question", "")).strip()
        if not question:
            raise GoalPlannerError("blocked decision requires a non-empty 'question'")
        return PlanResult(decision="blocked", question=question, note=note or question)

    if decision in ("sleep", "done"):
        return PlanResult(decision=decision, note=note)

    # decision == "act"
    raw_actions = parsed.get("actions")
    if not isinstance(raw_actions, list) or len(raw_actions) != 1:
        raise GoalPlannerError("act decision requires exactly one action")
    a = raw_actions[0]
    if not isinstance(a, dict):
        raise GoalPlannerError("action must be an object")
    tool = a.get("tool")
    if tool not in _VALID_TOOLS:
        raise GoalPlannerError(f"action.tool must be one of {_VALID_TOOLS}, got {tool!r}")
    g = str(a.get("goal", "")).strip()
    if not g:
        raise GoalPlannerError("action.goal must be non-empty")
    action = Action(
        engine="devclaw",
        tool=tool,
        goal=g,
        verify_cmd=(str(a["verify_cmd"]).strip() if a.get("verify_cmd") else None),
        open_pr=bool(a.get("open_pr", True)),
    )
    return PlanResult(decision="act", actions=[action], note=note or g)


async def plan(
    goal: Goal,
    status: GoalStatus,
    recent_log: str,
    steering: str,
    finished_detail: str,
    *,
    claude_caller: ClaudeCaller,
) -> PlanResult:
    """Run the next-action plan step. ``claude_caller`` is injected so tests stub
    the LLM."""
    prompt = build_prompt(goal, status, recent_log, steering, finished_detail)
    raw = await claude_caller(prompt)
    try:
        parsed = json.loads(extract_json(raw))
    except json.JSONDecodeError as exc:
        raise GoalPlannerError(f"planner emitted invalid JSON: {exc}", raw) from exc
    return validate(parsed)


def default_caller() -> ClaudeCaller:
    """The production cognition caller, bound to the goal-planner tier. Imported
    lazily from devclaw's shared ``claude --print`` factory so unit tests (which
    inject a fake) never touch the subprocess."""
    from .planner import claude_with_model

    return claude_with_model(GOAL_PLANNER_MODEL)
